// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLywze83OJZduwzS2ktjREmhQcsKVagGM',
    appId: '1:124051355104:web:7ba92c0dcb6abeea07e785',
    messagingSenderId: '124051355104',
    projectId: 'mahami-44274',
    authDomain: 'mahami-44274.firebaseapp.com',
    storageBucket: 'mahami-44274.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKBjWqE9VKnP8uYvJlMulK72qJ6PRut28',
    appId: '1:124051355104:android:df705d674d728fd807e785',
    messagingSenderId: '124051355104',
    projectId: 'mahami-44274',
    storageBucket: 'mahami-44274.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8mYUE3CbCmuua7m7uqVSAssszERaR_PE',
    appId: '1:124051355104:ios:25622a49770a40af07e785',
    messagingSenderId: '124051355104',
    projectId: 'mahami-44274',
    storageBucket: 'mahami-44274.firebasestorage.app',
    iosBundleId: 'com.example.mahami',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8mYUE3CbCmuua7m7uqVSAssszERaR_PE',
    appId: '1:124051355104:ios:25622a49770a40af07e785',
    messagingSenderId: '124051355104',
    projectId: 'mahami-44274',
    storageBucket: 'mahami-44274.firebasestorage.app',
    iosBundleId: 'com.example.mahami',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLywze83OJZduwzS2ktjREmhQcsKVagGM',
    appId: '1:124051355104:web:f3f291094c297c9007e785',
    messagingSenderId: '124051355104',
    projectId: 'mahami-44274',
    authDomain: 'mahami-44274.firebaseapp.com',
    storageBucket: 'mahami-44274.firebasestorage.app',
  );
}
