// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5veolayFLHMGCQezY97PQmU3kfoqGgcc',
    appId: '1:760887458914:web:e3276ea5d665b909c4a53b',
    messagingSenderId: '760887458914',
    projectId: 'fir-auth-app-5ade9',
    authDomain: 'fir-auth-app-5ade9.firebaseapp.com',
    storageBucket: 'fir-auth-app-5ade9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQTarXL-zlY0bDa4XP1vDdajk5NSMO5U',
    appId: '1:760887458914:android:d30ef1e3ce67dd82c4a53b',
    messagingSenderId: '760887458914',
    projectId: 'fir-auth-app-5ade9',
    storageBucket: 'fir-auth-app-5ade9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbGBXez5GUjG4p8xQUWxaAxEYL-lybJg4',
    appId: '1:760887458914:ios:0b6583554a2857d2c4a53b',
    messagingSenderId: '760887458914',
    projectId: 'fir-auth-app-5ade9',
    storageBucket: 'fir-auth-app-5ade9.firebasestorage.app',
    iosClientId: '760887458914-aapk2o5qvj4b778hat2co2to4m53jigf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseday16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbGBXez5GUjG4p8xQUWxaAxEYL-lybJg4',
    appId: '1:760887458914:ios:0b6583554a2857d2c4a53b',
    messagingSenderId: '760887458914',
    projectId: 'fir-auth-app-5ade9',
    storageBucket: 'fir-auth-app-5ade9.firebasestorage.app',
    iosClientId: '760887458914-aapk2o5qvj4b778hat2co2to4m53jigf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseday16',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5veolayFLHMGCQezY97PQmU3kfoqGgcc',
    appId: '1:760887458914:web:765bc96f1873a885c4a53b',
    messagingSenderId: '760887458914',
    projectId: 'fir-auth-app-5ade9',
    authDomain: 'fir-auth-app-5ade9.firebaseapp.com',
    storageBucket: 'fir-auth-app-5ade9.firebasestorage.app',
  );
}
